# Setup
title: middlee
description: "Personal website of data scientist Michael Lee."
url: http://middlee.com
baseurl: /
locale: en_US

# Jekyll configuration

permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments


# Plugin: jekyll-archives

jekyll-archives:
  enabled:
    - tags
    - year
  layouts:
    year: year_index
    tag: tag_index
  permalinks:
    year: /:year/
    tag: /tag/:name/


# Site owner

owner:
  name: Michael Lee
  email: mdlee12@gmail.com
  twitter: mlee_mke
  github: mdlee12
  github-repo: https://github.com/mdlee12/mdlee12.github.com
  google:
    ad-client: 
    ad-slot: 
    analytics: UA-58518999-1
    plus: 
    verify: 
  bio: ""
  avatar: .jpg # 160x160 px image for author byline

# Custom vars
current_version:  1.0.0
repo: https://github.com/mdlee12/mdlee12.github.com

download:
  source: https://github.com/twbs/bootstrap/archive/v3.3.2.zip
  dist: https://github.com/twbs/bootstrap/releases/download/v3.3.2/bootstrap-3.3.2-dist.zip
  sass: https://github.com/twbs/bootstrap-sass/archive/v3.3.2.tar.gz

cdn:
  css: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css
  css_theme:  https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css
  js: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js
