# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               middlee
tagline:             'Data Visualization, Analysis, and Statistical Musings'
description:         'Interested in learning more? Check out my <a href="https://github.com/mdlee12" target="_blank">Github</a>, follow me on <a href="https://twitter.com/mlee_mke" target="_blank">Twitter</a>, or connect with me on <a href="https://www.linkedin.com/in/middlee" target="_blank">Linkedin</a>.'
url:                 http://middlee.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Michael Lee
  url:               https://twitter.com/mlee_mke
  email:             mdlee12@gmail.com

# Custom vars
version:             1.0.0
