baseurl = "/"
languageCode = "en-us"
title = "Michael Lee"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "mikeleeco"
googleAnalytics = "UA-58518999-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Params]
  subtitle = "R and Data Visualization"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  relativeurls = true

[Author]
  name = "Michael Lee"
  email = "mdlee12@gmail.com"
  github = "mikeleeco"
  twitter = "mikeleeco"
  linkedin = "mikeleeco"
  stackoverflow = "users/5982900/michael-lee"

[[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 2

[[menu.main]]
    name = "Interactives"
    url = "/interactives"
    weight = 3

[[menu.main]]
    name = "Animation"
    url = "/animation"
    weight = 4

[[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 5

[taxonomies]
    tag = "tags"
    category = "categories"